CREATE TABLE T_LU_DIGITAL_FORM_DESCRIPTION
(
  FORM_NAME		VARCHAR2(150),
  FORM_DESC		VARCHAR2(100) NOT NULL
)
TABLESPACE ACCOUNT_D;


ALTER TABLE T_LU_DIGITAL_FORM_DESCRIPTION
  ADD CONSTRAINT pk_FORM_NAME PRIMARY KEY (FORM_NAME)
    USING INDEX TABLESPACE ACCOUNT_I;
	
GRANT SELECT ON T_LU_DIGITAL_FORM_DESCRIPTION to select_only_role;