/*

  Script:      050_BATCHatCAS_IT335_DML_RB.sql
  Schema:      BATCH@CAS
  Author:      siturrioz
  Date:        12/02/2019
  Purpose:     Rollback 050_BATCHatCAS_IT335_DML_ROsql

*/

SET TERMOUT ON
SET ECHO Off
SET LINESIZE 80
SET SERVEROUTPUT ON SIZE 10000

WHENEVER SQLERROR EXIT ROLLBACK

column filename new_val filename1 

SELECT SYS_CONTEXT('USERENV', 'INSTANCE_NAME')     filename
  FROM dual; 
  
spool  050_BATCHatCAS_IT335_DML_RB_&filename1..log

ALTER SESSION SET CURRENT_SCHEMA = BATCH;
 
SELECT 'current user is ' || USER || ' at '
  FROM dual;


SELECT TO_CHAR(SYSDATE, 'DD-Mon-YYYY HH24:MI:SS') date_
  FROM dual;

@DEL_T_BATCH_JOB_DIGITALFORMFAILURESINTERNALNOTIFICATION_PARAMS.sql;

@DEL_T_BATCH_JOB_DIGITALFORMFAILURESINTERNALNOTIFICATION.sql;

@DEL_T_BATCH_JOB_DIGITALFORMFAILURESCUSTOMERNOTIFICATION_PARAMS.sql;

@DEL_T_BATCH_JOB_DIGITALFORMFAILURESCUSTOMERNOTIFICATION.sql;


SELECT TO_CHAR(SYSDATE, 'DD-Mon-YYYY HH24:MI:SS') date_
  FROM dual;

sho ERRORS 
spo OFF 
